version: 0.0
os: linux
files:
  - source: \
    destination: /opt/HelloWorld
  - source: hello.service
    destination: /usr/lib/systemd/system/
hooks:
  BeforeInstall:
    - location: stop_server.sh
    - location: dotnet-install.sh
    - location: build.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_server.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: check_service.sh
      timeout: 180
      runas: root